# PDF Report Exporter
# Generates PDF reports from markdown files

param(
    [string]$InputFile = "",
    [string]$OutputDir = "",
    [switch]$ExportAllDaily,
    [switch]$ExportAllWeekly,
    [string]$OutputPath = (Join-Path (Join-Path (Join-Path $PSScriptRoot "..") "work-archive") "exports")
)

# Ensure output directory exists
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

function Convert-MarkdownToPDF($markdownFile, $outputFile) {
    Write-Host "Converting: $markdownFile" -ForegroundColor Yellow
    
    # Read markdown content
    $mdContent = Get-Content $markdownFile -Raw -Encoding UTF8
    
    # Convert markdown to HTML
    $htmlContent = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }
        h2 {
            color: #34495e;
            border-bottom: 2px solid #ecf0f1;
            padding-bottom: 8px;
        }
        h3 {
            color: #7f8c8d;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #3498db;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        code {
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Consolas', monospace;
        }
        pre {
            background-color: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }
        blockquote {
            border-left: 4px solid #3498db;
            padding-left: 20px;
            margin-left: 0;
            color: #7f8c8d;
        }
        ul, ol {
            padding-left: 30px;
        }
        li {
            margin: 5px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #95a5a6;
            font-size: 0.9em;
            text-align: center;
        }
        @media print {
            body { margin: 0; padding: 20px; }
            .footer { position: fixed; bottom: 0; }
        }
    </style>
</head>
<body>
    $mdContent
    <div class="footer">
        Generated by AI Work Archiver | $(Get-Date -Format "yyyy-MM-dd HH:mm")
    </div>
</body>
</html>
"@
    
    # Save HTML temporarily
    $tempHtml = [System.IO.Path]::ChangeExtension($outputFile, ".html")
    $htmlContent | Out-File $tempHtml -Encoding UTF8
    
    # Try to use browser to print to PDF
    Write-Host "  Note: Manual PDF conversion required" -ForegroundColor Gray
    Write-Host "  Open this file in browser and print to PDF: $tempHtml" -ForegroundColor Gray
    
    return $tempHtml
}

function Export-DailyReports($outputPath) {
    $dailyDir = Join-Path (Join-Path (Join-Path $PSScriptRoot "..") "work-archive") "daily-reports"
    
    if (-not (Test-Path $dailyDir)) {
        Write-Host "No daily reports found" -ForegroundColor Yellow
        return @()
    }
    
    $exportedFiles = @()
    
    # Get all markdown files
    $mdFiles = Get-ChildItem -Path $dailyDir -Recurse -Filter "*.md" | Sort-Object Name
    
    foreach ($mdFile in $mdFiles) {
        $outputFile = Join-Path $outputPath "$($mdFile.BaseName).pdf"
        $htmlFile = Convert-MarkdownToPDF $mdFile.FullName $outputFile
        $exportedFiles += $htmlFile
    }
    
    return $exportedFiles
}

function Export-WeeklyReports($outputPath) {
    $weeklyDir = Join-Path (Join-Path (Join-Path $PSScriptRoot "..") "work-archive") "weekly-reports"
    
    if (-not (Test-Path $weeklyDir)) {
        Write-Host "No weekly reports found" -ForegroundColor Yellow
        return @()
    }
    
    $exportedFiles = @()
    $mdFiles = Get-ChildItem -Path $weeklyDir -Filter "*.md" | Sort-Object Name
    
    foreach ($mdFile in $mdFiles) {
        $outputFile = Join-Path $outputPath "$($mdFile.BaseName).pdf"
        $htmlFile = Convert-MarkdownToPDF $mdFile.FullName $outputFile
        $exportedFiles += $htmlFile
    }
    
    return $exportedFiles
}

# Main logic
Write-Host "PDF Export Tool" -ForegroundColor Cyan
Write-Host "===============" -ForegroundColor Cyan

$allExported = @()

if ($ExportAllDaily) {
    Write-Host "`nExporting daily reports..." -ForegroundColor Yellow
    $exported = Export-DailyReports $OutputPath
    $allExported += $exported
    Write-Host "Exported $($exported.Count) daily reports" -ForegroundColor Green
}

if ($ExportAllWeekly) {
    Write-Host "`nExporting weekly reports..." -ForegroundColor Yellow
    $exported = Export-WeeklyReports $OutputPath
    $allExported += $exported
    Write-Host "Exported $($exported.Count) weekly reports" -ForegroundColor Green
}

if ($InputFile) {
    Write-Host "`nExporting single file..." -ForegroundColor Yellow
    if (Test-Path $InputFile) {
        $outputName = [System.IO.Path]::ChangeExtension((Split-Path $InputFile -Leaf), ".pdf")
        $outputFile = Join-Path $OutputPath $outputName
        $htmlFile = Convert-MarkdownToPDF $InputFile $outputFile
        $allExported += $htmlFile
        Write-Host "Exported: $htmlFile" -ForegroundColor Green
    } else {
        Write-Host "File not found: $InputFile" -ForegroundColor Red
    }
}

if ($allExported.Count -gt 0) {
    Write-Host "`nExport Summary" -ForegroundColor Cyan
    Write-Host "==============" -ForegroundColor Cyan
    Write-Host "Total files: $($allExported.Count)" -ForegroundColor White
    Write-Host "Output directory: $OutputPath" -ForegroundColor White
    Write-Host "`nNext steps:" -ForegroundColor Yellow
    Write-Host "1. Open each HTML file in browser" -ForegroundColor Gray
    Write-Host "2. Press Ctrl+P to print" -ForegroundColor Gray
    Write-Host "3. Select 'Save as PDF' as printer" -ForegroundColor Gray
    Write-Host "4. Save the PDF file" -ForegroundColor Gray
} else {
    Write-Host "`nNo files exported. Use -ExportAllDaily or -ExportAllWeekly" -ForegroundColor Yellow
}
